USE [master];

CREATE DATABASE dboDinassaur;

USE [dboDinassaur];

CREATE TABLE age (
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(60) NOT NULL,
	yBeg INTEGER NOT NULL,
	yEnd INTEGER NOT NULL
);

CREATE TABLE grupos (
	id INTEGER PRIMARY KEY NOT NULL IDENTITY,
	nome VARCHAR(50) NOT NULL
);

CREATE TABLE dinossaur (
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(25) NOT NULL,
	fk_grupo INTEGER NOT NULL,
	toneladas INTEGER NOT NULL,
	yDescoberta INTEGER NOT NULL,
	descrobidor VARCHAR(30) NOT NULL,
	fk_age INTEGER NOT NULL,
	yVivo INTEGER NOT NULL,
	pais VARCHAR(50) NOT NULL,

	FOREIGN KEY (fk_grupo) REFERENCES grupos(id),
);

CREATE TABLE fk_dino_age (
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	fk_age INTEGER NOT NULL,
	fk_dinossaur INTEGER NOT NULL,

	FOREIGN KEY (fk_age) REFERENCES age(id),
	FOREIGN KEY (fk_dinossaur) REFERENCES dinossaur(id)
);
