CREATE DATABASE Teste_ADONET;

-- Criando um Login para se conectar ao SQL SERVER
CREATE LOGIN TesteADONET WITH PASSWORD = 'senha12345';

USE Teste_ADONET;

CREATE TABLE Pessoas (
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(50) NOT NULL,
	idade INTEGER NOT NULL
);